services:
  app:
    build: .
    container_name: solara_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://solar:solar_pass@db:5432/solar_calculator?schema=public
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: solar_postgres
    restart: always
    environment:
      POSTGRES_USER: solar
      POSTGRES_PASSWORD: solar_pass
      POSTGRES_DB: solar_calculator
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U solar -d solar_calculator"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
